export const translationReportLanguages = [
  ["ar-SA", "العربية"],
  ["co-FR", "Corsu"],
  ["da-DK", "Dansk"],
  ["de-CH", "Deutsch (Schweiz)"],
  ["de-DE", "Deutsch"],
  ["el-GR", "Ελληνικά"],
  ["en", "English (United States)"],
  ["en-GB", "English (United Kingdom)"],
  ["es", "Español"],
  ["es-419", "Español (Latinoamérica)"],
  ["es-AR", "Español (Argentina)"],
  ["es-CO", "Español (Colombia)"],
  ["es-DO", "Español (República Dominicana)"],
  ["es-EQ", "Español (Ecuador)"],
  ["es-ES", "Español (España)"],
  ["es-MX", "Español (México)"],
  ["es-PR", "Español (Puerto Rico)"],
  ["es-US", "Español (Estados Unidos)"],
  ["fr-FR", "Français"],
  ["fur-IT", "Furlan"],
  ["gl-ES", "Galego"],
  ["he-IL", "עברית"],
  ["hi-IN", "हिन्दी"],
  ["id-ID", "Bahasa Indonesia"],
  ["it-CH", "Italiano (Svizzera)"],
  ["it-IT", "Italiano"],
  ["ja-JP", "日本語"],
  ["ko-KR", "한국어"],
  ["ms-MY", "Bahasa Melayu"],
  ["nl-NL", "Nederlands"],
  ["pl-PL", "Polski"],
  ["pt-BR", "Português (Brasil)"],
  ["pt-PT", "Português (Portugal)"],
  ["ru-RU", "Русский"],
  ["sv-SE", "Svenska"],
  ["th-TH", "ไทย"],
  ["tr-TR", "Türkçe"],
  ["vi-VN", "Tiếng Việt"],
  ["zh-CN", "简体中文"],
  ["zh-TW", "繁體中文"],
].map(([value, label]) => ({ label, value }));
